### ISSUE TITLE
Users

### ISSUE THREAD

**Issue by mhartian** [Asutosh11/CollegeClassifieds#1]
how can i add user?

**Comment by Asutosh11** [comment]
hi mhartian. This app has got no functionality for adding user. You can directly Post ads without being logged in. No login/sign up functionality is there.

**Comment by squalk** [comment]
Colleges tend to want at least some user control so they can enforce standards or keep out banned individuals. Could you provide an API to connect this application with a school's main login system?

**Comment by Asutosh11** [comment]
@squalk This project is an old one. The kind of functionality you are mentioning can be built but I'm no longer working on this project actively. So I may consider this option as a part of rework to be done in future.
